name: firebase_auth_utility
description: This versatile Flutter package simplifies the integration of essential features into your mobile app. It includes ready-to-use components for authentication and push notifications.
version: 0.0.3
homepage: https://github.com/zingworks-kuldeep/firebase_auth_utility/tree/master/example
repository: https://github.com/zingworks-kuldeep/firebase_auth_utility
issue_tracker: https://github.com/zingworks-kuldeep/firebase_auth_utility/issues

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0