// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcnlBk_7u7poJ0SegPIdYvxsZAlNk7m1c',
    appId: '1:996650551553:web:a3c169ad3615da986d7300',
    messagingSenderId: '996650551553',
    projectId: 'firebase-auth-util',
    authDomain: 'fir-auth-util.firebaseapp.com',
    storageBucket: 'firebase-auth-util.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vby_1oOIBPN6KjJDbUPuhc3NfcIE7W4',
    appId: '1:996650551553:android:0d862b7f0a6c4e636d7300',
    messagingSenderId: '996650551553',
    projectId: 'firebase-auth-util',
    storageBucket: 'firebase-auth-util.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_D_nmsJ6K9v4rLoWNFMP2mDwYpdJL5RE',
    appId: '1:996650551553:ios:05f15aeab88f0ca66d7300',
    messagingSenderId: '996650551553',
    projectId: 'firebase-auth-util',
    storageBucket: 'firebase-auth-util.appspot.com',
    androidClientId: '996650551553-dqcqt435d31va12q9tvisel44logs0kj.apps.googleusercontent.com',
    iosClientId: '996650551553-7kd7e848u4e9phb5tdtvqn25fhac062v.apps.googleusercontent.com',
    iosBundleId: 'com.zingworks.firebaseAuthUtil',
  );
}
